---
title: "Welcome to Functional Programming Blog"
description: |
  Welcome to our class project blog
author:
  - name: SG, AK, BR, JW 
    url: https://s-gluck.github.io/funprog_blog
    affiliation: University of Oregon
    affiliation_url: https://uoregon.edu
date: 06-10-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

Welcome to our class project blog. This blog was created as part of the final project for EDUC610 [
Functional Programming with R
](https://uo-datasci-specialization.github.io/c3-fun_program2020/index.html) taught by [Daniel Anderson](https://github.com/datalorax) at the University of Oregon. The blog contains tutorial type guides on the basic of writing function in R to automate your data workflow and analysis. 

The authors of the blog are: 

[Stephanie Gluck](https://github.com/s-gluck)

[Akhila Nekkanti](https://github.com/akhilanekkanti1) 

[Brock Rowley](https://github.com/RowleyBrock) 

[Joanna Wright](https://github.com/jhwrigh23) 



### The following blog post contain guides related to iteration and writing functions: 

SG: add link once finalized and authors please edit. 

1) To setup your project and load data, by Brock Rowley

2) To to subset data and output basic descriptives, by Stephanie Gluck and Akhila Nekkanti

3) To visualize your data, by Joanna Wright

### About the Data 

For the tutorial, we will use the [COVID Community Measures](https://www.kaggle.com/gustavomodelli/covid-community-measures) dataset from Kaggle. We hope that you will be able to generalize the function we covered to be applicable to your own dataset. The current dataset contains Community Mobility Reports describing community activities in a variety of settings from Google and the incidence of COVID-19 diagnosis and fatalities from John Hopkins CSSE. 

Community activity is defined as the change in activity from the baseline days. A baseline day is the median value from the 5‑week period between January 3rd to February 6th, 2020. 

